### ISSUE TITLE
`length_squared` and `normalize_or_zero` methods for vectors

### ISSUE THREAD

**Issue by JoJoJet** [simonask/glamour#16]
These two methods are very useful for avoiding extra work in some cases, and guaranteeing correctness of the output. They would be very useful to have on `glamour` vectors.  

I've tried implementing this on a fork but I'm having trouble making sense of all the macros.

**Comment by simonask** [comment]
> I've tried implementing this on a fork but I'm having trouble making sense of all the macros.

I don't blame you, it's pretty involved. 😅

I'll make an issue to make this more approachable.
