### ISSUE TITLE
Release version for glam 0.28

### ISSUE THREAD

**Issue by stefnotch** [simonask/glamour#55]
I would love to upgrade my glam library, seeing as how other libraries such as `encase` depend on it.

Getting a new version of glamour, which depends on glam 0.28, would be amazing :)

**Comment by simonask** [comment]
Back from holidays, expect progress soon! :-)

**Comment by simonask** [comment]
glamour 0.12.0 has been released with support for glam 0.28.0.

Please note that this also contains several breaking changes. Let me know if these are causing big issues for you. 😄

**Comment by simonask** [comment]
I also just released 0.13.0 for glam 0.29.0, if that interests you.

**Comment by stefnotch** [comment]
Awesome, thank you very much!
