### ISSUE TITLE
Missing functions in upgrade 0.11 -> 0.14

### ISSUE THREAD

**Issue by v0x0g** [simonask/glamour#59]
I'm trying to upgrade from `v0.11 -> v0.14`.

Right now I'm getting errors because there is no method `Vector3::cross()`. I have looked at the [docs](https://docs.rs/glamour/latest/glamour/index.html?search=cross) and I cannot see a cross product function anywhere, although a dot-product clearly exists [here](https://docs.rs/glamour/latest/glamour/struct.Vector3.html#method.dot).
I even went so far as to download the entire crate and run `cargo expand`. There is no concrete implementation of `cross()` in the expanded output.

~I'm also getting errors because the `ToRaw/FromRaw` traits have vanished~. This is solved by the `Transparent` trait (from reading the changelog).

~The same is happening for `Swizzle`.~ Solved with the `glamour::Vec3Swizzles` trait.

Could I please have some help with this?

**Comment by simonask** [comment]
Thanks for this report, I'll do a pass to make sure everything is properly exposed.

**Comment by simonask** [comment]
Fixed in 0.14.1, should be available on crates.io now. :-)
